### ISSUE TITLE
Option to only select mandatory content

### ISSUE THREAD

**Issue by matatata** [davidteren/lpx_links#10]
Hi,
first of all thank you very much for creating this useful program. I was looking for a way to be able to only select the mandatory packages that Logic Pro X would install on first launch. This way one can get started faster when setting up a new machine. Seems that the required information is already available in the json you generate so I tried to leverage that by myself with the following change https://github.com/matatata/lpx_links/commit/2d4cb67b3ffb9c5f92995c59e1c3ecc0ec4cb848 .
Turns out that it does indeed what I wanted (Tested with 10.4.1). Just wanted you to know. Maybe you'll want to incorporate this as feature in future. Thanks.
Regards 
Matatata

**Comment by davidteren** [comment]
Hi Matatata
Thanks for the idea. I have implemented it & credited you.

**Comment by matatata** [comment]
Thank you very much!
