### ISSUE TITLE
mandatory_download_links.txt is empty

### ISSUE THREAD

**Issue by Pauligrinder** [davidteren/lpx_links#11]
After running the command in the readme, the mandary-list is empty. The all-list contains 61 entries though.

**Comment by davidteren** [comment]
@Pauligrinder, which version of Logic Pro X do you have installed?

**Comment by Pauligrinder** [comment]
It won't tell me because it doesn't start. It downloads some stuff and when the download finishes it just closes. Which is why I wanted to try your script - when I googled, I found a post where someone suggested to try downloading separately.
