### ISSUE TITLE
Invalid package path

### ISSUE THREAD

**Issue by M1crolog1c** [davidteren/lpx_links#14]
I'm completely new to MacOS and I need help. I have downloaded everything successfully but when I try to run the install command I get the error:

installer: Error - the package path specified was invalid: '../LogicX/*.pkg'.

Everything else was a success, I can see all of the downloaded packages in the downloads folder. I have tried changing the terminal directory but it's still the same.

**Comment by brianllun** [comment]
same here

**Comment by Salvadi** [comment]
Hi, you need to modify the command a little bit. Igot it working with: 
`sudo ./download_install.sh ~/lpx_download_links/all_download_links.txt ~/Downloads/logic_content `

hope this helps
