### ISSUE TITLE
Not an issue... just a big THANK YOU

### ISSUE THREAD

**Issue by inspiredearth** [davidteren/lpx_links#15]
@davidteren and @davidt-imqs 
**Thanks so much for creating this script.**

I've gone through huge issues with the ridiculous library manager in Logic Pro, resulting in downloading the library files (in full) at least 5 or 6 times (over my relatively slow 4G broadband connection).  It's been a huge time-waster.

Being able to download all the PKGs, and store them, and install them all in one hit (I used [installpgk](https://github.com/henri/installpkg) for that), has been a huge help.

So again, thank you for making this script available. It's much appreciated, all these years later.

**Comment by Cheerstoast** [comment]
@davidteren Thanks for the package URLs list! It must have taken ages for you to get them. This made installing sound libraries on old versions of garageband or logic pro x possible.

Below is a bash script I created that installs all sound libraries, provided that:
1. You have around 30GB of free disk space
2. You are willing to wait for 1 - 2 hours for the packages to be downloaded, installed, and then deleted
3. You switch to root with *sudo su* first.

AND, yes, you may copy and paste these in the terminal to execute it.

        cd ~/Downloads; mkdir -p lpx_links/app ; cd lpx_links/app ; curl -#L https://go$
        
        # wget -c -i ~/Desktop/lpx_download_links/all_download_links.txt -d ~/Downloads$
        
        for pkg in $HOME/Downloads/lpx_links/app/*.pkg; do
            echo Installing $pkg file...
            installer -pkg $pkg -target /
        done
        
        rm -r ~/Desktop/lpx_download_links ~/Downloads/lpx_links
