### ISSUE TITLE
Rabbithole - Please advise!

### ISSUE THREAD

**Issue by rubbersoul71** [davidteren/lpx_links#16]
David,
Firstly thanks for putting this together - I had the common issue of Logic Pro refusing to download/install the standard + additional sound files hence I found you and lpx_links.
AFAIK, I've managed to download all the sound files (with a couple of errors/exceptions) and these are all in my Download folder. They are all .pkg files.
I'm now having trouble unpackaging them.
I've followed the scripts and advice already here on the issues page here but with no success.

Can you suggest how I can unpackage these files? Presumably, once unpacked, they will still need to go into the _imac/library/application support/logic_ folder?

I've seen people mention that I need to unpack the files with a specific Terminal instruction but my knowledge is pretty poor when it comes to Terminal so any sort of idiot's guide would be appreciated!

Best,
Jim

**Comment by wtLau** [comment]
bump

**Comment by wtLau** [comment]
try this 
To install all the downloaded packages use the following command:  
  
```sh
# for mandatory files 
 sudo ~/Downloads/lpx_links/app/download_install.sh ~/Desktop/lpx_download_links/mandatory_download_links.txt ~/Downloads/logic_content 
```  

```sh
# for all the packages
 sudo ~/Downloads/lpx_links/app/download_install.sh ~/Desktop/lpx_download_links/all_download_links.txt ~/Downloads/logic_content 
```

**Comment by davidteren** [comment]
@wtLau thanks for
