### ISSUE TITLE
A simple help

### ISSUE THREAD

**Issue by gustavoguri** [davidteren/lpx_links#9]
Hey David, 

I came to this page from the logic pro forum links.

So i downloaded all the library logic files using the Firefox Add-on DownThemAll. I want a Terminal command/script that install all the package files. Your script download and install. I just want to install all of them. Can you write a script/command for this? All the files are in Downloads folder. I am not a programmer. Thanks for the help.

**Comment by davidteren** [comment]
I am still looking to do this as soon as I have free time.

**Comment by davidteren** [comment]
Busy adding this feature.

**Comment by Sameto** [comment]
@davidteren That would be awesome. Thanks in advance.

**Comment by davidteren** [comment]
Hi, I've added download instructions using aria2 in the Readme.
